// Declared explicitly (rather than relying on next-env.d.ts's generic "*.png"
// ambient module) because next-env.d.ts is gitignored and only generated by
// running `next dev`/`next build` — a fresh checkout running `tsc --noEmit`
// before any Next.js command (as CI does) wouldn't have it yet.
declare module "leaflet/dist/images/marker-icon-2x.png" {
  const src: string;
  export default src;
}

declare module "leaflet/dist/images/marker-icon.png" {
  const src: string;
  export default src;
}

declare module "leaflet/dist/images/marker-shadow.png" {
  const src: string;
  export default src;
}
